# Generated by Django 2.1.2 on 2018-11-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181106_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlinekeyword',
            name='entity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='headlinekeyword',
            name='type_nnp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='headlinekeyword',
            name='wiki',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
